version: 2
jobs:
  lint:
    working_directory: ~/project
    docker:
      - image: circleci/node:8
    environment:
      REVIEWDOG_VERSION: 0.9.8
    steps:
      - checkout
      - run:
          name: Install Reviewdog
          command: curl -fSL https://github.com/haya14busa/reviewdog/releases/download/$REVIEWDOG_VERSION/reviewdog_linux_amd64 -o reviewdog && chmod +x ./reviewdog
      - run: |
          npm install
          rm -rf ./node_modules/react-native/local-cli/core/__fixtures__/files/package.json
      - run: npx eslint . -f compact | ./reviewdog -f=eslint-compact -ci="circle-ci"
      - persist_to_workspace:
          root: ~/project
          paths:
            - node_modules

  android:
    working_directory: ~/project/android
    docker:
      - image: circleci/android:api-27-node8-alpha
    steps:
      - checkout:
          path: ~/project
      - attach_workspace:
          at: ~/project
      - restore_cache:
         key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}
      - run:
         name: Set License
         command: |
           mkdir -p $ANDROID_HOME/licenses
           echo -e "d56f5187479451eabf01fb78af6dfcb131a6481e" > $ANDROID_HOME/licenses/android-sdk-license
           echo -e "84831b9409646a918e30573bab4c9c91346d8abd" > $ANDROID_HOME/licenses/android-sdk-preview-license
      - run:
         name: Download Dependencies
         command: ./gradlew androidDependencies
      - run:
         name: Build APK
         command: ./gradlew assembleRelease
      - store_artifacts:
         path: app/build/outputs/apk
         destination: apk
      - save_cache:
         paths:
           - ~/.gradle
         key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}

workflows:
  version: 2
  node-android:
    jobs:
      - lint
      - android:
          requires:
            - lint