version: 2
jobs:
  android:
    working_directory: ~/project/
    docker:
      - image: circleci/android:api-27-node8-alpha
    steps:
      - checkout
      - run: |
          npm install
          cp index.d.ts node_modules/react-navigation-redux-helpers/
          rm -rf ./node_modules/react-native/local-cli/core/__fixtures__/files/package.json
          cd ./android
      - restore_cache:
         key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}
      - run:
         name: Set License
         command: |
           mkdir -p $ANDROID_HOME/licenses
           echo -e "d56f5187479451eabf01fb78af6dfcb131a6481e" > $ANDROID_HOME/licenses/android-sdk-license
           echo -e "84831b9409646a918e30573bab4c9c91346d8abd" > $ANDROID_HOME/licenses/android-sdk-preview-license
      - run:
         name: Download Dependencies
         command: ./gradlew androidDependencies
      - run:
         name: Build APK
         command: ./gradlew assembleRelease
      - store_artifacts:
         path: app/build/outputs/apk
         destination: apk
      - save_cache:
         paths:
           - ~/.gradle
         key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}

workflows:
  version: 2
  node-android:
    jobs:
      - android