version: 2
jobs:
  compile:
    working_directory: ~/project
    docker:
      - image: circleci/node:8
    steps:
      - checkout
      - run: |
          npm install
          cp index.d.ts node_modules/react-navigation-redux-helpers/
          rm -rf ./node_modules/react-native/local-cli/core/__fixtures__/files/package.json
      - run: npx tsc --skiplibCheck
      - persist_to_workspace:
          root: ~/project
          paths:
            - build
            - node_modules

  android:
    working_directory: ~/project/android
    docker:
      - image: circleci/android:api-27-node8-alpha
    steps:
      - checkout: 
          path: ~/project
      - attach_workspace:
          at: ~/project
      - run:
          name: Decrypted keys
          command: |
              openssl aes-256-cbc -d -k $SIGNATURE_DECRYPT_KEY -in secret.properties.encrypted -out secret.properties
              openssl aes-256-cbc -d -k $SIGNATURE_DECRYPT_KEY -in keystores/release.keystore.encrypted -out keystores/release.keystore
      - restore_cache:
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}
      - run:
          name: Set License
          command: |
              mkdir -p $ANDROID_HOME/licenses
              echo -e "d56f5187479451eabf01fb78af6dfcb131a6481e" > $ANDROID_HOME/licenses/android-sdk-license
              echo -e "84831b9409646a918e30573bab4c9c91346d8abd" > $ANDROID_HOME/licenses/android-sdk-preview-license
      - run:
          name: Download Dependencies
          command: ./gradlew androidDependencies
      - run:
          name: Build APK
          command: ./gradlew assembleRelease
      - store_artifacts:
          path: app/build/outputs/apk
          destination: apk
      - save_cache:
          paths:
            - ~/.gradle
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}
      - run:
          name: Deploy
          command: |
              [ "$CIRCLE_BRANCH" != "master" ] && exit
              ../deploy.sh

workflows:
  version: 2
  node-android:
    jobs:
      - compile
      - android: 
          requires: 
            - compile
